Algoritmo "Are do retangulo"

Var
base, altura, area, perimetro, diagonal : real



Inicio
escreva("Digite o valor a base do retangulo: ")
leia(base)
escreva("Digite a altura do retangulo : ")
leia (altura)

area <- base * altura

escreval("Area do retangulo = ", area)

perimetro <- ( 2 * base) + (2 * altura)

escreval("Valor do Perimetro =", perimetro)

diagonal <- raizQ(exp(base,2) + exp(altura, 2))

escreva( "Valor do perimetro =" , diagonal:8:2 )

Fimalgoritmo