Algoritmo "multiplos"

Var

HoraI, HoraF, Duracao : inteiro


Inicio

escreval("digite a hora inicial do jogo")
  leia(HoraI)
escreval("digite a hora final do jogo")
leia(HoraF)

se HoraI >  Horaf entao
duracao <- (24 - HoraI ) + HoraF)
senao
 se HoraI < Horaf entao
 Duracao <- HoraF - HoraI
 senao
 se HoraF = HoraI entao
 Duracao <-  24
 senao
 escreva("NUMERO INVALIDO")
 
 
 fimse
 fimse
 fimse

   escreva("O JOGO DUROU ",Duracao, " HORA(S)")

Fimalgoritmo